package parser.beaconPromotions;

import java.util.HashMap;
import java.util.Map;

public class UpchargeConstants {
	
	 public static Map<String, String> UPCHARGE_MAP =new HashMap<String, String>();
	    static {
	//UPCHARGE_MAP.put("Charge ID ","Charge Nam@@@@@Discount#####USD1_____USD2_____USD3_____USD4_____USD5_____USD6_____USD7_____USD8_____USD9");
	UPCHARGE_MAP.put("1","Add'l Decoraction Method: Engraved Logo (Badge)@@@@@A#####2.93_____2.7_____2.53_____2.37_____2.19");
	UPCHARGE_MAP.put("2","Add'l Decoraction Method: Engraved Logo (Desk Plate)@@@@@A#####3.71_____3.45_____3.24_____3.04_____2.84_____2.63");
	UPCHARGE_MAP.put("3","Add'l Decoration Method: Decoration Run (Envelopes)@@@@@G#####0.07");
	UPCHARGE_MAP.put("4","Add'l Decoration Method: Full Color Medallion Run@@@@@G#####2.5");
	UPCHARGE_MAP.put("5","Add'l Decoration Method: Gift Box Decoration@@@@@G#####0.35");
	UPCHARGE_MAP.put("6","Add'l Decoration Method: Large Full Color Transfer@@@@@G#####1.75");
	UPCHARGE_MAP.put("7","Add'l Decoration Method: Small Full Color Transfer@@@@@G#####1.1");
	UPCHARGE_MAP.put("8","Add'l Decoration Method: Splash of Color@@@@@G#####0.4");
	UPCHARGE_MAP.put("9","Add'l Decoration Method: Splash of Color Gift Box@@@@@G#####0.75");
	UPCHARGE_MAP.put("10","Add'l Decoration Option: 2nd Side Imprint@@@@@A#####0.55_____0.41_____0.34_____0.27_____0.2");
	UPCHARGE_MAP.put("11","Add'l Decoration Option: 2nd Side Imprint@@@@@A#####1.59");
	UPCHARGE_MAP.put("12","Add'l Decoration Option: 2nd Side Photo@@@@@A#####1.86");
	UPCHARGE_MAP.put("13","Add'l Decoration Option: Additional Color Run@@@@@G#####0.06");
	UPCHARGE_MAP.put("14","Add'l Decoration Option: Additional Color Run@@@@@G#####0.11");
	UPCHARGE_MAP.put("15","Add'l Decoration Option: Additional Color Run@@@@@G#####0.15");
	UPCHARGE_MAP.put("16","Add'l Decoration Option: Additional Color Run@@@@@G#####0.17");
	UPCHARGE_MAP.put("17","Add'l Decoration Option: Additional Color Run@@@@@G#####0.2");
	UPCHARGE_MAP.put("18","Add'l Decoration Option: Additional Color Run@@@@@G#####0.35");
	UPCHARGE_MAP.put("19","Add'l Decoration Option: Additional Color Run@@@@@G#####0.75");
	UPCHARGE_MAP.put("20","Add'l Decoration Option: Additional Color Run@@@@@G#####13_____12_____11_____10");
	UPCHARGE_MAP.put("21","Add'l Decoration Option: Additional Location Run@@@@@G#####0.25");
	UPCHARGE_MAP.put("22","Add'l Decoration Option: Additional Location Run@@@@@G#####0.32");
	UPCHARGE_MAP.put("23","Add'l Decoration Option: Additional Location Run@@@@@G#####0.35");
	UPCHARGE_MAP.put("24","Add'l Decoration Option: Additional Location Run@@@@@A#####0.48_____0.27_____0.17_____0.13");
	UPCHARGE_MAP.put("25","Add'l Decoration Option: Additional Location Run@@@@@G#####0.75");
	UPCHARGE_MAP.put("26","Add'l Decoration Option: Additional Location Run (Deboss)@@@@@G#####4");
	UPCHARGE_MAP.put("27","Add'l Decoration Option: Additional Location Run (Dye Sub Cover)@@@@@G#####55_____52.5_____42_____35");
	UPCHARGE_MAP.put("28","Add'l Decoration Option: Additional Location Run (SS Cover/Runner/Banner)@@@@@G#####45_____35_____27.5_____17.5");
	UPCHARGE_MAP.put("29","Add'l Decoration Option: Additional Side Run@@@@@C#####0.6");
	UPCHARGE_MAP.put("30","Add'l Decoration Option: Additional Side Run@@@@@A#####2.5_____2.14_____1.44_____1.03_____0.9");
	UPCHARGE_MAP.put("31","Add'l Decoration Option: Additional Side Run CRDHT482@@@@@A#####0.75_____0.61_____0.54_____0.47_____0.41");
	UPCHARGE_MAP.put("32","Add'l Decoration Option: Barcoding@@@@@A#####0.48_____0.27_____0.17_____0.13");
	UPCHARGE_MAP.put("33","Add'l Decoration Option: Barcoding@@@@@A#####0.55_____0.48_____0.27_____0.17_____0.13");
	UPCHARGE_MAP.put("34","Add'l Decoration Option: Bleed@@@@@A#####0.6");
	UPCHARGE_MAP.put("35","Add'l Decoration Option: Consecutive Numbering@@@@@A#####0.48_____0.27_____0.17_____0.13");
	UPCHARGE_MAP.put("36","Add'l Decoration Option: Consecutive Numbering@@@@@A#####0.55_____0.48_____0.27_____0.17_____0.13");
	UPCHARGE_MAP.put("37","Attachment: 108636 Cubicle Holder@@@@@C#####4.67");
	UPCHARGE_MAP.put("38","Attachment: DESK28A Metal Desk Holder@@@@@C#####6.99");
	UPCHARGE_MAP.put("39","Attachment: Rhinestone Lanyard@@@@@C#####4.75");
	UPCHARGE_MAP.put("40","Attachment: Safety Break-Away@@@@@C#####0.45");
	UPCHARGE_MAP.put("41","Attachment: Strap Clip@@@@@C#####0.5");
	UPCHARGE_MAP.put("42","Attachment: Super Grip Magnet@@@@@C#####2.25");
	UPCHARGE_MAP.put("43","Attachment: TAPE@@@@@C#####0.25");
	UPCHARGE_MAP.put("44","Attachment: VEL02@@@@@C#####1.2");
	UPCHARGE_MAP.put("45","Attachment: Wall208A Metal Wall Holder@@@@@C#####4.31");
	UPCHARGE_MAP.put("46","Attachment: Wall210A Metal Wall Holder@@@@@C#####4.9");
	UPCHARGE_MAP.put("47","Attachmment: Bulldog Clip@@@@@C#####0.6");
	UPCHARGE_MAP.put("48","Attachmment: DESK210A Metal Desk Holder@@@@@C#####7.93");
	UPCHARGE_MAP.put("49","Attachmment: DESK210P Molded Plastic Desk Holder@@@@@C#####6.07");
	UPCHARGE_MAP.put("50","Attachmment: DESK28P Molded Plastic Desk Holder@@@@@C#####4.55");
	UPCHARGE_MAP.put("51","Attachmment: DS01 Desk Stand@@@@@C#####2.25");
	UPCHARGE_MAP.put("52","Attachmment: FT02@@@@@C#####1.1");
	UPCHARGE_MAP.put("53","Attachmment: Lanyard@@@@@C#####0.6");
	UPCHARGE_MAP.put("54","Attachmment: Military Clutch@@@@@C#####0.42");
	UPCHARGE_MAP.put("55","Calendar PMS Match@@@@@G#####24");
	UPCHARGE_MAP.put("56","Extended Size Pricing (starting at XLT or 2XL, multiplies per extended size)@@@@@C#####12.5");
	UPCHARGE_MAP.put("57","Additional Decoration Setup@@@@@G#####55");
	UPCHARGE_MAP.put("58","Less than Minimum@@@@@G#####55");
	UPCHARGE_MAP.put("59","Less than Minimum Planners@@@@@G#####45");
	UPCHARGE_MAP.put("60","Misc: 2 batteries bulk@@@@@D#####3.6");
	UPCHARGE_MAP.put("61","Misc: 2 batteries inserted@@@@@D#####4.2");
	UPCHARGE_MAP.put("62","Misc: 3 batteries bulk@@@@@D#####5.4");
	UPCHARGE_MAP.put("63","Misc: 3 batteries inserted@@@@@D#####6.3");
	UPCHARGE_MAP.put("64","Misc: 4 batteries bulk@@@@@D#####7.2");
	UPCHARGE_MAP.put("65","Misc: 4 batteries inserted@@@@@D#####8.4");
	UPCHARGE_MAP.put("66","Misc: Badge Warehouse LTM@@@@@G#####40");
	UPCHARGE_MAP.put("67","Misc: Badge Warehouse PRO Setup (for programs needing higher reporting/access options)@@@@@G#####62.5");
	UPCHARGE_MAP.put("68","Misc: Badge Warehouse Release Charge (First Class Mail)@@@@@G#####2.75");
	UPCHARGE_MAP.put("69","Misc: Badge Warehouse Release Charge (Shipper ID provided for each release)@@@@@G#####1");
	UPCHARGE_MAP.put("70","Misc: Business Card Pocket@@@@@C#####1.62_____1.54_____1.18_____0.94");
	UPCHARGE_MAP.put("71","Misc: CLKDMS1 Pack of 10 Lenses@@@@@A#####19.99");
	UPCHARGE_MAP.put("72","Misc: CLKDMS2 Pack of 10 Additional Lenses@@@@@A#####19.99");
	UPCHARGE_MAP.put("73","Misc: CLKINS1 1 Sheet of Inserts (6 inserts/sheet)@@@@@A#####0.94");
	UPCHARGE_MAP.put("74","Misc: CLKINS2 1 Sheet of Inserts (5 inserts/sheet)@@@@@A#####1.02");
	UPCHARGE_MAP.put("75","Misc: Paper Insert Sheets@@@@@A#####2");
	UPCHARGE_MAP.put("76","Misc: Planner Copy Change@@@@@G#####12");
	UPCHARGE_MAP.put("77","Misc: Plastic Insert Sheets@@@@@A#####2");
	UPCHARGE_MAP.put("78","Misc: SIG101@@@@@G#####36");
	UPCHARGE_MAP.put("79","Misc: SIG102@@@@@G#####52");
	UPCHARGE_MAP.put("80","Misc: SIG103@@@@@G#####36");
	UPCHARGE_MAP.put("81","Misc: SIG105@@@@@G#####221");
	UPCHARGE_MAP.put("82","Misc: SIG107@@@@@G#####106");
	UPCHARGE_MAP.put("83","Misc: SIGSLHCC@@@@@G#####51");
	UPCHARGE_MAP.put("84","Misc: Table Cover Bag@@@@@G#####12");
	UPCHARGE_MAP.put("85","Personalization: Add'l Line Personalization Desk Plate@@@@@A#####4.13_____2.84_____2.63_____2.43_____2.22_____2.03");
	UPCHARGE_MAP.put("86","Personalization: Add'l Line Personalization Metal NB@@@@@A#####2.36_____2.21_____2.1_____2.03_____1.94");
	UPCHARGE_MAP.put("87","Personalization: Add'l Line Personalization Plastic NB@@@@@A#####1.85_____1.73_____1.62_____1.57_____1.53");
	UPCHARGE_MAP.put("88","Personalization: Add'l Line Personalization Plastic NB@@@@@A#####2.22_____1.85_____1.73_____1.62_____1.57_____1.53");
	UPCHARGE_MAP.put("89","Personalization: Bag Tag Personalization@@@@@C#####0.59_____0.33_____0.3_____0.28");
	UPCHARGE_MAP.put("90","Personalization: Debossed Initials@@@@@G#####5");
	UPCHARGE_MAP.put("91","Personalization: Factory Typeset@@@@@G#####0.5");
	UPCHARGE_MAP.put("92","Personalization: Supplied in Text File Format@@@@@G#####0.25");
	UPCHARGE_MAP.put("93","PMS Match@@@@@G#####55");
	UPCHARGE_MAP.put("94","Setup Calendars Add'l Color@@@@@G#####24");
	UPCHARGE_MAP.put("95","Setup Commercial Planners Add'l Color@@@@@G#####31");
	UPCHARGE_MAP.put("96","Setup Debossing@@@@@G#####110");
	UPCHARGE_MAP.put("97","Setup Decorated Envelopes@@@@@G#####30");
	UPCHARGE_MAP.put("98","Setup Engraved Only@@@@@G#####25");
	UPCHARGE_MAP.put("99","Setup per color, per location@@@@@G#####55");
	UPCHARGE_MAP.put("100","Setup per color, per location@@@@@G#####85");
	UPCHARGE_MAP.put("101","Setup Planners per color, per location@@@@@G#####36");
	UPCHARGE_MAP.put("102","Shipping: Early Release@@@@@G#####40");
	UPCHARGE_MAP.put("103","Special Fabrication: Dome S1@@@@@A#####1");
	UPCHARGE_MAP.put("104","Special Fabrication: Dome S2@@@@@A#####1.5");
	UPCHARGE_MAP.put("105","Special Fabrication: Dome S3@@@@@A#####2");
	UPCHARGE_MAP.put("106","Special Fabrication: Doming per Sq Inch@@@@@C#####0.33");
	UPCHARGE_MAP.put("107","Special Fabrication: Hole Punch Per Hole, Per Piece, 100 hole minimum billed@@@@@C#####0.16");
	UPCHARGE_MAP.put("108","Special Fabrication: MAG@@@@@C#####0.31");
	UPCHARGE_MAP.put("109","Special Fabrication: P/S Tape 467 per Sq. Inch@@@@@C#####0.04");
	UPCHARGE_MAP.put("110","Special Fabrication: P/S Tape 468 per Sq. Inch@@@@@C#####0.06");
	UPCHARGE_MAP.put("111","Special Fabrication: Per Corner, per piece@@@@@C#####0.08");
	UPCHARGE_MAP.put("112","Special Fabrication: Setup@@@@@C#####25");
	UPCHARGE_MAP.put("113","Special Fabrication: Slot Run@@@@@C#####0.16");
	UPCHARGE_MAP.put("114","Special Fabrication: Thermal Bend@@@@@A#####2.11_____2_____1.94_____1.87_____1.79_____1.68");
	UPCHARGE_MAP.put("115","Special Packaging: 101174 Bulk@@@@@G#####0.16");
	UPCHARGE_MAP.put("116","Special Packaging: 101174 Inserted@@@@@G#####0.24");
	UPCHARGE_MAP.put("117","Special Packaging: 103400 Envelopes Shipped Bulk@@@@@G#####0.2");
	UPCHARGE_MAP.put("118","Special Packaging: 103400 Envelopes Shipped Inserted@@@@@G#####0.32");
	UPCHARGE_MAP.put("119","Special Packaging: 103401 shipped bulk@@@@@G#####0.25");
	UPCHARGE_MAP.put("120","Special Packaging: 103401 shipped inserted@@@@@G#####0.37");
	UPCHARGE_MAP.put("121","Special Packaging: 103402 Envelopes Shipped Bulk@@@@@G#####0.25");
	UPCHARGE_MAP.put("122","Special Packaging: 103402 Envelopes Shipped with Planners Inserted@@@@@G#####0.37");
	UPCHARGE_MAP.put("123","Special Packaging: 103403 Envelopes Shipped Bulk@@@@@G#####0.3");
	UPCHARGE_MAP.put("124","Special Packaging: 103403 Envelopes with Planners Inserted@@@@@G#####0.42");
	UPCHARGE_MAP.put("125","Special Packaging: 103404 Chipboard Mailers Shipped Bulk@@@@@G#####0.6");
	UPCHARGE_MAP.put("126","Special Packaging: 103404 Chipboard Mailers with Planners Inserted@@@@@G#####0.72");
	UPCHARGE_MAP.put("127","Special Packaging: 103406 Chipboard Mailer Shipped Bulk@@@@@G#####0.75");
	UPCHARGE_MAP.put("128","Special Packaging: 103406 Chipboard Mailer with Planners Inserted@@@@@G#####0.87");
	UPCHARGE_MAP.put("129","Special Packaging: 103407 Tuc Mailer Shipped Bulk@@@@@G#####0.45");
	UPCHARGE_MAP.put("130","Special Packaging: 103407 Tuc Mailer Shipped with Planners Inserted@@@@@G#####0.57");
	UPCHARGE_MAP.put("131","Special Packaging: 103409 Gusset Mailer Shipped Bulk@@@@@G#####1.2");
	UPCHARGE_MAP.put("132","Special Packaging: 103409 Gusset Mailer with Planners Inserted@@@@@G#####1.32");
	UPCHARGE_MAP.put("133","Special Packaging: Kraft Tube 101172@@@@@G#####0.55");
	UPCHARGE_MAP.put("134","Special Packaging: Kraft Tube 101173@@@@@G#####0.55");
	UPCHARGE_MAP.put("135","Special Packaging: N800@@@@@C#####2.5");
	UPCHARGE_MAP.put("136","Special Packaging: N801@@@@@C#####3.4");
	UPCHARGE_MAP.put("137","Special Packaging: N802@@@@@C#####5");
	UPCHARGE_MAP.put("138","Special Packaging: N803@@@@@C#####5.9");
	UPCHARGE_MAP.put("139","Special Packaging: N804@@@@@C#####7.5");
	UPCHARGE_MAP.put("140","Special Packaging: Rustic Tin RT790@@@@@C#####15");
	UPCHARGE_MAP.put("141","Special Packaging: Rustic Tin RT800@@@@@C#####15");
	UPCHARGE_MAP.put("142","Special Packaging: Rustic Tin RT803@@@@@C#####14.5");
	UPCHARGE_MAP.put("143","Special Packaging: Rustic Tin RT804@@@@@C#####17");
	UPCHARGE_MAP.put("144","Special Packaging: Rustic Tin RT810@@@@@C#####19.5");
	UPCHARGE_MAP.put("145","Special Packaging: Rustic Tin RT817@@@@@C#####24");
	UPCHARGE_MAP.put("146","Special Packaging: Rustic Tin RT820@@@@@C#####25");
	UPCHARGE_MAP.put("147","Special Packaging: Rustic Tin RT821@@@@@C#####28.5");
	UPCHARGE_MAP.put("148","Special Packaging: Rustic Tin RT822@@@@@C#####32");
	UPCHARGE_MAP.put("149","Special Packaging: Rustic Tin RT825@@@@@C#####36.5");
	UPCHARGE_MAP.put("150","Special Packaging: Rustic Tin RT830@@@@@C#####39.5");
	UPCHARGE_MAP.put("151","Special Packaging: Rustic Tin RT835@@@@@C#####43");
	UPCHARGE_MAP.put("152","Special Fabrication: Special Cutting, Per Cut, per piece@@@@@C#####0.26");
	UPCHARGE_MAP.put("154","Wash-Up@@@@@G#####18");
	UPCHARGE_MAP.put("156","Setup Per Color, Per Location@@@@@G#####25");
	UPCHARGE_MAP.put("157","Setup Per Color@@@@@G#####25");
	UPCHARGE_MAP.put("158","Setup Per Location@@@@@G#####25");
	UPCHARGE_MAP.put("159","Setup Per Color@@@@@G#####55");
	UPCHARGE_MAP.put("160","Setup Per Location@@@@@G#####55");
	UPCHARGE_MAP.put("161","Setup@@@@@G#####25");
	UPCHARGE_MAP.put("162","Setup@@@@@G#####85");
	UPCHARGE_MAP.put("163","Setup@@@@@G#####55");
	UPCHARGE_MAP.put("164","Add'l Decoration Option: Additional Color Run@@@@@G#####10");
	UPCHARGE_MAP.put("165","Add'l Decoraiton Option: Additional Location Run@@@@@G#####0.1");
	UPCHARGE_MAP.put("166","Add'l Decoraiton Option: Additional Location Run@@@@@C#####0.6");
	UPCHARGE_MAP.put("167","Setup per color@@@@@G#####85");
	UPCHARGE_MAP.put("168","Corporate Gift Handling (per location, including first)@@@@@G#####12.5");
	    }
}
