package parser.beaconPromotions;

import java.util.HashMap;
import java.util.Map;

public class UpchargeConstants {
	
	 public static Map<String, String> UPCHARGE_MAP =new HashMap<String, String>();
	 public static Map<String, String> MATERIAL_MAP =new HashMap<String, String>();
	 public static Map<String, String> BCNCOLOR_MAP =new HashMap<String, String>();
	    static {
	        //UPCHARGE_MAP.put("Charge ID ","Charge Nam@@@@@Discount#####USD1_____USD2_____USD3_____USD4_____USD5_____USD6_____USD7_____USD8_____USD9");
	    	UPCHARGE_MAP.put("1","IMMD:Add'l Decoraction Method: Engraved Logo (Badge)@@@@@A@@@@@2.93___2.7___2.53___2.37___2.19");
	    	UPCHARGE_MAP.put("2","IMMD:Add'l Decoraction Method: Engraved Logo (Desk Plate)@@@@@A@@@@@3.71___3.45___3.24___3.04___2.84___2.63");
	    	UPCHARGE_MAP.put("3","IMMD:Add'l Decoration Method: Decoration Run (Envelopes)@@@@@G@@@@@0.07");
	    	UPCHARGE_MAP.put("4","IMMD:Add'l Decoration Method: Full Color Medallion Run@@@@@G@@@@@2.5");
	    	UPCHARGE_MAP.put("5","IMMD:Add'l Decoration Method: Gift Box Decoration@@@@@G@@@@@0.35");
	    	UPCHARGE_MAP.put("6","IMMD:Add'l Decoration Method: Large Full Color Transfer@@@@@G@@@@@1.75");
	    	UPCHARGE_MAP.put("7","IMMD:Add'l Decoration Method: Small Full Color Transfer@@@@@G@@@@@1.1");
	    	UPCHARGE_MAP.put("8","IMMD:Add'l Decoration Method: Splash of Color@@@@@G@@@@@0.4");
	    	UPCHARGE_MAP.put("9","IMMD:Add'l Decoration Method: Splash of Color Gift Box@@@@@G@@@@@0.75");
	    	UPCHARGE_MAP.put("10","IMOP:Add'l Decoration Option: 2nd Side Imprint@@@@@A@@@@@0.55___0.41___0.34___0.27___0.2");
	    	UPCHARGE_MAP.put("11","IMOP:Add'l Decoration Option: 2nd Side Imprint@@@@@A@@@@@1.59");
	    	UPCHARGE_MAP.put("12","IMOP:Add'l Decoration Option: 2nd Side Photo@@@@@A@@@@@1.86");
	    	UPCHARGE_MAP.put("13","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.06");
	    	UPCHARGE_MAP.put("14","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.11");
	    	UPCHARGE_MAP.put("15","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.15");
	    	UPCHARGE_MAP.put("16","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.17");
	    	UPCHARGE_MAP.put("17","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.2");
	    	UPCHARGE_MAP.put("18","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.35");
	    	UPCHARGE_MAP.put("19","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@0.75");
	    	UPCHARGE_MAP.put("20","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@13___12___11___10");
	    	UPCHARGE_MAP.put("21","IMOP:Add'l Decoration Option: Additional Location Run@@@@@G@@@@@0.25");
	    	UPCHARGE_MAP.put("22","IMOP:Add'l Decoration Option: Additional Location Run@@@@@G@@@@@0.32");
	    	UPCHARGE_MAP.put("23","IMOP:Add'l Decoration Option: Additional Location Run@@@@@G@@@@@0.35");
	    	UPCHARGE_MAP.put("24","IMOP:Add'l Decoration Option: Additional Location Run@@@@@A@@@@@0.48___0.27___0.17___0.13");
	    	UPCHARGE_MAP.put("25","IMOP:Add'l Decoration Option: Additional Location Run@@@@@G@@@@@0.75");
	    	UPCHARGE_MAP.put("26","IMOP:Add'l Decoration Option: Additional Location Run (Deboss)@@@@@G@@@@@4");
	    	UPCHARGE_MAP.put("27","IMOP:Add'l Decoration Option: Additional Location Run (Dye Sub Cover)@@@@@G@@@@@55___52.5___42___35");
	    	UPCHARGE_MAP.put("28","IMOP:Add'l Decoration Option: Additional Location Run (SS Cover/Runner/Banner)@@@@@G@@@@@45___35___27.5___17.5");
	    	UPCHARGE_MAP.put("29","IMOP:Add'l Decoration Option: Additional Side Run@@@@@C@@@@@0.6");
	    	UPCHARGE_MAP.put("30","IMOP:Add'l Decoration Option: Additional Side Run@@@@@A@@@@@2.5___2.14___1.44___1.03___0.9");
	    	UPCHARGE_MAP.put("31","IMOP:Add'l Decoration Option: Additional Side Run CRDHT482@@@@@A@@@@@0.75___0.61___0.54___0.47___0.41");
	    	UPCHARGE_MAP.put("32","IMOP:Add'l Decoration Option: Barcoding@@@@@A@@@@@0.48___0.27___0.17___0.13");
	    	UPCHARGE_MAP.put("33","IMOP:Add'l Decoration Option: Barcoding@@@@@A@@@@@0.55___0.48___0.27___0.17___0.13");
	    	UPCHARGE_MAP.put("34","IMOP:Add'l Decoration Option: Bleed@@@@@A@@@@@0.6");
	    	UPCHARGE_MAP.put("35","IMOP:Add'l Decoration Option: Consecutive Numbering@@@@@A@@@@@0.48___0.27___0.17___0.13");
	    	UPCHARGE_MAP.put("36","IMOP:Add'l Decoration Option: Consecutive Numbering@@@@@A@@@@@0.55___0.48___0.27___0.17___0.13");
	    	UPCHARGE_MAP.put("37","PROP:Attachment: 108636 Cubicle Holder@@@@@C@@@@@4.67");
	    	UPCHARGE_MAP.put("38","PROP:Attachment: DESK28A Metal Desk Holder@@@@@C@@@@@6.99");
	    	UPCHARGE_MAP.put("39","PROP:Attachment: Rhinestone Lanyard@@@@@C@@@@@4.75");
	    	UPCHARGE_MAP.put("40","PROP:Attachment: Safety Break-Away@@@@@C@@@@@0.45");
	    	UPCHARGE_MAP.put("41","PROP:Attachment: Strap Clip@@@@@C@@@@@0.5");
	    	UPCHARGE_MAP.put("42","PROP:Attachment: Super Grip Magnet@@@@@C@@@@@2.25");
	    	UPCHARGE_MAP.put("43","PROP:Attachment: TAPE@@@@@C@@@@@0.25");
	    	UPCHARGE_MAP.put("44","PROP:Attachment: VEL02@@@@@C@@@@@1.2");
	    	UPCHARGE_MAP.put("45","PROP:Attachment: Wall208A Metal Wall Holder@@@@@C@@@@@4.31");
	    	UPCHARGE_MAP.put("46","PROP:Attachment: Wall210A Metal Wall Holder@@@@@C@@@@@4.9");
	    	UPCHARGE_MAP.put("47","PROP:Attachmment: Bulldog Clip@@@@@C@@@@@0.6");
	    	UPCHARGE_MAP.put("48","PROP:Attachmment: DESK210A Metal Desk Holder@@@@@C@@@@@7.93");
	    	UPCHARGE_MAP.put("49","PROP:Attachmment: DESK210P Molded Plastic Desk Holder@@@@@C@@@@@6.07");
	    	UPCHARGE_MAP.put("50","PROP:Attachmment: DESK28P Molded Plastic Desk Holder@@@@@C@@@@@4.55");
	    	UPCHARGE_MAP.put("51","PROP:Attachmment: DS01 Desk Stand@@@@@C@@@@@2.25");
	    	UPCHARGE_MAP.put("52","PROP:Attachmment: FT02@@@@@C@@@@@1.1");
	    	UPCHARGE_MAP.put("53","PROP:Attachmment: Lanyard@@@@@C@@@@@0.6");
	    	UPCHARGE_MAP.put("54","PROP:Attachmment: Military Clutch@@@@@C@@@@@0.42");
	    	UPCHARGE_MAP.put("55","IMMD:Calendar PMS Match@@@@@G@@@@@24");
	    	UPCHARGE_MAP.put("56","PROP:Extended Size Pricing (starting at XLT or 2XL, multiplies per extended size)@@@@@C@@@@@12.5");
	    	UPCHARGE_MAP.put("57","IMOP:Additional Decoration Setup@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("58","LMIN:Less than Minimum@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("59","LMIN:Less than Minimum Planners@@@@@G@@@@@45");
	    	UPCHARGE_MAP.put("60","PROP:Misc: 2 batteries bulk@@@@@D@@@@@3.6");
	    	UPCHARGE_MAP.put("61","PROP:Misc: 2 batteries inserted@@@@@D@@@@@4.2");
	    	UPCHARGE_MAP.put("62","PROP:Misc: 3 batteries bulk@@@@@D@@@@@5.4");
	    	UPCHARGE_MAP.put("63","PROP:Misc: 3 batteries inserted@@@@@D@@@@@6.3");
	    	UPCHARGE_MAP.put("64","PROP:Misc: 4 batteries bulk@@@@@D@@@@@7.2");
	    	UPCHARGE_MAP.put("65","PROP:Misc: 4 batteries inserted@@@@@D@@@@@8.4");
	    	UPCHARGE_MAP.put("66","PROP:Misc: Badge Warehouse LTM@@@@@G@@@@@40");
	    	UPCHARGE_MAP.put("67","PROP:Misc: Badge Warehouse PRO Setup (for programs needing higher reporting/access options)@@@@@G@@@@@62.5");
	    	UPCHARGE_MAP.put("68","PROP:Misc: Badge Warehouse Release Charge (First Class Mail)@@@@@G@@@@@2.75");
	    	UPCHARGE_MAP.put("69","PROP:Misc: Badge Warehouse Release Charge (Shipper ID provided for each release)@@@@@G@@@@@1");
	    	UPCHARGE_MAP.put("70","PROP:Misc: Business Card Pocket@@@@@C@@@@@1.62___1.54___1.18___0.94");
	    	UPCHARGE_MAP.put("71","PROP:Misc: CLKDMS1 Pack of 10 Lenses@@@@@A@@@@@19.99");
	    	UPCHARGE_MAP.put("72","PROP:Misc: CLKDMS2 Pack of 10 Additional Lenses@@@@@A@@@@@19.99");
	    	UPCHARGE_MAP.put("73","PROP:Misc: CLKINS1 1 Sheet of Inserts (6 inserts/sheet)@@@@@A@@@@@0.94");
	    	UPCHARGE_MAP.put("74","PROP:Misc: CLKINS2 1 Sheet of Inserts (5 inserts/sheet)@@@@@A@@@@@1.02");
	    	UPCHARGE_MAP.put("75","PROP:Misc: Paper Insert Sheets@@@@@A@@@@@2");
	    	UPCHARGE_MAP.put("76","PROP:Misc: Planner Copy Change@@@@@G@@@@@12");
	    	UPCHARGE_MAP.put("77","PROP:Misc: Plastic Insert Sheets@@@@@A@@@@@2");
	    	UPCHARGE_MAP.put("78","PROP:Misc: SIG101@@@@@G@@@@@36");
	    	UPCHARGE_MAP.put("79","PROP:Misc: SIG102@@@@@G@@@@@52");
	    	UPCHARGE_MAP.put("80","PROP:Misc: SIG103@@@@@G@@@@@36");
	    	UPCHARGE_MAP.put("81","PROP:Misc: SIG105@@@@@G@@@@@221");
	    	UPCHARGE_MAP.put("82","PROP:Misc: SIG107@@@@@G@@@@@106");
	    	UPCHARGE_MAP.put("83","PROP:Misc: SIGSLHCC@@@@@G@@@@@51");
	    	UPCHARGE_MAP.put("84","PROP:Misc: Table Cover Bag@@@@@G@@@@@12");
	    	UPCHARGE_MAP.put("85","IMMD:Personalization: Add'l Line Personalization Desk Plate@@@@@A@@@@@4.13___2.84___2.63___2.43___2.22___2.03");
	    	UPCHARGE_MAP.put("86","IMMD:Personalization: Add'l Line Personalization Metal NB@@@@@A@@@@@2.36___2.21___2.1___2.03___1.94");
	    	UPCHARGE_MAP.put("87","IMMD:Personalization: Add'l Line Personalization Plastic NB@@@@@A@@@@@1.85___1.73___1.62___1.57___1.53");
	    	UPCHARGE_MAP.put("88","IMMD:Personalization: Add'l Line Personalization Plastic NB@@@@@A@@@@@2.22___1.85___1.73___1.62___1.57___1.53");
	    	UPCHARGE_MAP.put("89","IMMD:Personalization: Bag Tag Personalization@@@@@C@@@@@0.59___0.33___0.3___0.28");
	    	UPCHARGE_MAP.put("90","IMMD:Personalization: Debossed Initials@@@@@G@@@@@5");
	    	UPCHARGE_MAP.put("91","IMMD:Personalization: Factory Typeset@@@@@G@@@@@0.5");
	    	UPCHARGE_MAP.put("92","IMMD:Personalization: Supplied in Text File Format@@@@@G@@@@@0.25");
	    	UPCHARGE_MAP.put("93","IMMD:PMS Match@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("94","IMMD:Setup Calendars Add'l Color@@@@@G@@@@@24");
	    	UPCHARGE_MAP.put("95","IMMD:Setup Commercial Planners Add'l Color@@@@@G@@@@@31");
	    	UPCHARGE_MAP.put("96","IMMD:Setup Debossing@@@@@G@@@@@110");
	    	UPCHARGE_MAP.put("97","IMMD:Setup Decorated Envelopes@@@@@G@@@@@30");
	    	UPCHARGE_MAP.put("98","IMMD:Setup Engraved Only@@@@@G@@@@@25");
	    	UPCHARGE_MAP.put("99","IMMD:Setup per color, per location@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("100","IMMD:Setup per color, per location@@@@@G@@@@@85");
	    	UPCHARGE_MAP.put("101","IMMD:Setup Planners per color, per location@@@@@G@@@@@36");
	    	UPCHARGE_MAP.put("102","SHOP:Shipping: Early Release@@@@@G@@@@@40");
	    	UPCHARGE_MAP.put("103","PROP:Special Fabrication: Dome S1@@@@@A@@@@@1");
	    	UPCHARGE_MAP.put("104","PROP:Special Fabrication: Dome S2@@@@@A@@@@@1.5");
	    	UPCHARGE_MAP.put("105","PROP:Special Fabrication: Dome S3@@@@@A@@@@@2");
	    	UPCHARGE_MAP.put("106","PROP:Special Fabrication: Doming per Sq Inch@@@@@C@@@@@0.33");
	    	UPCHARGE_MAP.put("107","PROP:Special Fabrication: Hole Punch Per Hole, Per Piece, 100 hole minimum billed@@@@@C@@@@@0.16");
	    	UPCHARGE_MAP.put("108","PROP:Special Fabrication: MAG@@@@@C@@@@@0.31");
	    	UPCHARGE_MAP.put("109","PROP:Special Fabrication: P/S Tape 467 per Sq. Inch@@@@@C@@@@@0.04");
	    	UPCHARGE_MAP.put("110","PROP:Special Fabrication: P/S Tape 468 per Sq. Inch@@@@@C@@@@@0.06");
	    	UPCHARGE_MAP.put("111","PROP:Special Fabrication: Per Corner, per piece@@@@@C@@@@@0.08");
	    	UPCHARGE_MAP.put("112","PROP:Special Fabrication: Setup@@@@@C@@@@@25");
	    	UPCHARGE_MAP.put("113","PROP:Special Fabrication: Slot Run@@@@@C@@@@@0.16");
	    	UPCHARGE_MAP.put("114","PROP:Special Fabrication: Thermal Bend@@@@@A@@@@@2.11___2___1.94___1.87___1.79___1.68");
	    	UPCHARGE_MAP.put("115","PCKG:Special Packaging: 101174 Bulk@@@@@G@@@@@0.16");
	    	UPCHARGE_MAP.put("116","PCKG:Special Packaging: 101174 Inserted@@@@@G@@@@@0.24");
	    	UPCHARGE_MAP.put("117","PCKG:Special Packaging: 103400 Envelopes Shipped Bulk@@@@@G@@@@@0.2");
	    	UPCHARGE_MAP.put("118","PCKG:Special Packaging: 103400 Envelopes Shipped Inserted@@@@@G@@@@@0.32");
	    	UPCHARGE_MAP.put("119","PCKG:Special Packaging: 103401 shipped bulk@@@@@G@@@@@0.25");
	    	UPCHARGE_MAP.put("120","PCKG:Special Packaging: 103401 shipped inserted@@@@@G@@@@@0.37");
	    	UPCHARGE_MAP.put("121","PCKG:Special Packaging: 103402 Envelopes Shipped Bulk@@@@@G@@@@@0.25");
	    	UPCHARGE_MAP.put("122","PCKG:Special Packaging: 103402 Envelopes Shipped with Planners Inserted@@@@@G@@@@@0.37");
	    	UPCHARGE_MAP.put("123","PCKG:Special Packaging: 103403 Envelopes Shipped Bulk@@@@@G@@@@@0.3");
	    	UPCHARGE_MAP.put("124","PCKG:Special Packaging: 103403 Envelopes with Planners Inserted@@@@@G@@@@@0.42");
	    	UPCHARGE_MAP.put("125","PCKG:Special Packaging: 103404 Chipboard Mailers Shipped Bulk@@@@@G@@@@@0.6");
	    	UPCHARGE_MAP.put("126","PCKG:Special Packaging: 103404 Chipboard Mailers with Planners Inserted@@@@@G@@@@@0.72");
	    	UPCHARGE_MAP.put("127","PCKG:Special Packaging: 103406 Chipboard Mailer Shipped Bulk@@@@@G@@@@@0.75");
	    	UPCHARGE_MAP.put("128","PCKG:Special Packaging: 103406 Chipboard Mailer with Planners Inserted@@@@@G@@@@@0.87");
	    	UPCHARGE_MAP.put("129","PCKG:Special Packaging: 103407 Tuc Mailer Shipped Bulk@@@@@G@@@@@0.45");
	    	UPCHARGE_MAP.put("130","PCKG:Special Packaging: 103407 Tuc Mailer Shipped with Planners Inserted@@@@@G@@@@@0.57");
	    	UPCHARGE_MAP.put("131","PCKG:Special Packaging: 103409 Gusset Mailer Shipped Bulk@@@@@G@@@@@1.2");
	    	UPCHARGE_MAP.put("132","PCKG:Special Packaging: 103409 Gusset Mailer with Planners Inserted@@@@@G@@@@@1.32");
	    	UPCHARGE_MAP.put("133","PCKG:Special Packaging: Kraft Tube 101172@@@@@G@@@@@0.55");
	    	UPCHARGE_MAP.put("134","PCKG:Special Packaging: Kraft Tube 101173@@@@@G@@@@@0.55");
	    	UPCHARGE_MAP.put("135","PCKG:Special Packaging: N800@@@@@C@@@@@2.5");
	    	UPCHARGE_MAP.put("136","PCKG:Special Packaging: N801@@@@@C@@@@@3.4");
	    	UPCHARGE_MAP.put("137","PCKG:Special Packaging: N802@@@@@C@@@@@5");
	    	UPCHARGE_MAP.put("138","PCKG:Special Packaging: N803@@@@@C@@@@@5.9");
	    	UPCHARGE_MAP.put("139","PCKG:Special Packaging: N804@@@@@C@@@@@7.5");
	    	UPCHARGE_MAP.put("140","PCKG:Special Packaging: Rustic Tin RT790@@@@@C@@@@@15");
	    	UPCHARGE_MAP.put("141","PCKG:Special Packaging: Rustic Tin RT800@@@@@C@@@@@15");
	    	UPCHARGE_MAP.put("142","PCKG:Special Packaging: Rustic Tin RT803@@@@@C@@@@@14.5");
	    	UPCHARGE_MAP.put("143","PCKG:Special Packaging: Rustic Tin RT804@@@@@C@@@@@17");
	    	UPCHARGE_MAP.put("144","PCKG:Special Packaging: Rustic Tin RT810@@@@@C@@@@@19.5");
	    	UPCHARGE_MAP.put("145","PCKG:Special Packaging: Rustic Tin RT817@@@@@C@@@@@24");
	    	UPCHARGE_MAP.put("146","PCKG:Special Packaging: Rustic Tin RT820@@@@@C@@@@@25");
	    	UPCHARGE_MAP.put("147","PCKG:Special Packaging: Rustic Tin RT821@@@@@C@@@@@28.5");
	    	UPCHARGE_MAP.put("148","PCKG:Special Packaging: Rustic Tin RT822@@@@@C@@@@@32");
	    	UPCHARGE_MAP.put("149","PCKG:Special Packaging: Rustic Tin RT825@@@@@C@@@@@36.5");
	    	UPCHARGE_MAP.put("150","PCKG:Special Packaging: Rustic Tin RT830@@@@@C@@@@@39.5");
	    	UPCHARGE_MAP.put("151","PCKG:Special Packaging: Rustic Tin RT835@@@@@C@@@@@43");
	    	UPCHARGE_MAP.put("152","IMOP:Special Fabrication: Special Cutting, Per Cut, per piece@@@@@C@@@@@0.26");
	    	UPCHARGE_MAP.put("154","IMOP:Wash-Up@@@@@G@@@@@18");
	    	UPCHARGE_MAP.put("156","IMMD:Setup Per Color, Per Location@@@@@G@@@@@25");
	    	UPCHARGE_MAP.put("157","IMMD:Setup Per Color@@@@@G@@@@@25");
	    	UPCHARGE_MAP.put("158","IMMD:Setup Per Location@@@@@G@@@@@25");
	    	UPCHARGE_MAP.put("159","IMMD:Setup Per Color@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("160","IMMD:Setup Per Location@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("161","IMMD:Setup@@@@@G@@@@@25");
	    	UPCHARGE_MAP.put("162","IMMD:Setup@@@@@G@@@@@85");
	    	UPCHARGE_MAP.put("163","IMMD:Setup@@@@@G@@@@@55");
	    	UPCHARGE_MAP.put("164","IMOP:Add'l Decoration Option: Additional Color Run@@@@@G@@@@@10");
	    	UPCHARGE_MAP.put("165","IMOP:Add'l Decoraiton Option: Additional Location Run@@@@@G@@@@@0.1");
	    	UPCHARGE_MAP.put("166","IMOP:Add'l Decoraiton Option: Additional Location Run@@@@@C@@@@@0.6");
	    	UPCHARGE_MAP.put("167","IMMD:Setup per color@@@@@G@@@@@85");
	    	UPCHARGE_MAP.put("168","SHOP:Corporate Gift Handling (per location, including first)@@@@@G@@@@@12.5");
	    	
	MATERIAL_MAP.put("Value","Code");
	MATERIAL_MAP.put("Full Grain Cowhide","Leather");
	MATERIAL_MAP.put("Distressed Buffalo Hide","Leather");
	MATERIAL_MAP.put("Full Grain Cowhide, 18 oz. beige canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Full Grain Washed Cowhide, 18 oz washed brown canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("16 oz. Washed Beige Cotton Canvas, Genuine Leather, Vegan Leather","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Full Grain Buffalo Hide, 18 oz. Forest Green Canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("16 oz Washed Blue Colorfast Cotton Canvas, Split Leather","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Full Grain Buffalo Hide, 18 oz. beige canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("300 denier polyester oxford water resistant fabric, Full Grain Buffalo Hide","Leather:Combo:Polyester");
	MATERIAL_MAP.put("16 oz. Washed Green and Realtree Xtra Cotton Canvas, Genuine Leather, Vegan Leather","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Leather and Charcoal Grey Wool/Polyester Blend","Blend:Wool::Polyester:");
	MATERIAL_MAP.put("Full Grain Washed Cowhide","Leather");
	MATERIAL_MAP.put("Distressed Cowhide, 18 oz. Forest Green Canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Grey Wool, Polyester, Genuine Cowhide","Leather:Combo:Polyester");
	MATERIAL_MAP.put("1200D Water Resistant Black Polyester, hardcover EVA, full grain cowhide","Leather:Combo:Polyester");
	MATERIAL_MAP.put("Koskin","Other");
	MATERIAL_MAP.put("Full Grain Drum Dyed Cowhide","Leather");
	MATERIAL_MAP.put("Pull Up Buffalo Hide","Leather");
	MATERIAL_MAP.put("Full Grain Drum Dyed Cowhide, Vegetable Tanned Full Grain Cowhide","Leather");
	MATERIAL_MAP.put("16 oz. Washed Green Cotton Canvas, Genuine Leather, Vegan Leather","Leather:Combo:Canvas");
	MATERIAL_MAP.put("Pull Up Buffalo Hide with 18 oz. Brown Cotton Canvas","Leather:Combo:Canvas");
	MATERIAL_MAP.put("16 oz. Washed Brown Cotton Canvas, Full Grain Cowhide, Vegan Leather","Leather:Combo:Canvas");
	MATERIAL_MAP.put("BPA Free Plastic","Plastic");
	MATERIAL_MAP.put("Vegetable Tanned Full Grain Cowhide","Leather");
	MATERIAL_MAP.put("New Zealand lambskin.","Leather");
	MATERIAL_MAP.put("Nappa Leather","Leather");
	MATERIAL_MAP.put("Vintage Nappa","Leather");
	MATERIAL_MAP.put("Lambskin","Leather");
	MATERIAL_MAP.put("65/35 Poly/Cotton","Blend:Polyester:65:Cotton:35");
	MATERIAL_MAP.put("1200D Water Resistant Black Polyester, 10 oz. Realtree Xtra Camo Cotton Duck, Full Grain Cowhide","Leather:Combo:Polyester");
	MATERIAL_MAP.put("100% Polyester.  8.8 oz. per sq. yard.  Flame retardant NFPA 701 Standard.","Polyester");
	MATERIAL_MAP.put("100% Polyester.  5 oz. per sq. yard.  Flame retardant NFPA 701 Standard.","Polyester");
	MATERIAL_MAP.put("100% Polyester, 4.13 oz per sq yard","Polyester");
	MATERIAL_MAP.put(" fabric.","Other Fabric");
	MATERIAL_MAP.put("White No Curl","Other");
	MATERIAL_MAP.put("White 10 oz. Vinyl, Fiberglass and Plastic","Vinyl:Combo:Plastic");
	MATERIAL_MAP.put("White 10 oz. Vinyl","Vinyl");
	MATERIAL_MAP.put("Fiberglass and Plastic","Other:Combo:Plastic");
	MATERIAL_MAP.put("White 13 oz. Smooth Vinyl, Fiberglass","Vinyl:Combo:Plastic");
	MATERIAL_MAP.put("White 13 oz. Smooth Vinyl","Vinyl");
	MATERIAL_MAP.put("Fiberglass","Other");
	MATERIAL_MAP.put("White Polyester Knit Fabric, Carbon Composite","Polyester");
	MATERIAL_MAP.put("White Polyester Knit Fabric","Polyester");
	MATERIAL_MAP.put("Carbon Composite","Other");
	MATERIAL_MAP.put("White Polyester Flag Fabric","Polyester");
	MATERIAL_MAP.put("White Polyester Flag Fabric, Carbon Composite, Metal","Polyester:Combo:Other");
	MATERIAL_MAP.put("White Polyester Knit Fabric, Aluminum","Polyester:Combo:Aluminum");
	MATERIAL_MAP.put("White Polyester Knit Fabric, Anodized Aluminum","Polyester:Combo:Aluminum");
	MATERIAL_MAP.put("Anodized Aluminum","Aluminum");
	MATERIAL_MAP.put("1/16 White Plastic","Plastic");
	MATERIAL_MAP.put("1/16 non-metallic 2-ply plastic","Plastic");
	MATERIAL_MAP.put("1/16 Metallic 2-ply Plastic","Plastic");
	MATERIAL_MAP.put("1/16 2-ply plastic","Plastic");
	MATERIAL_MAP.put(".020 Aluminum","Aluminum");
	MATERIAL_MAP.put(".020 Brass","Brass");
	MATERIAL_MAP.put(".020 Frosted Brass, .020 Frosted Nickle","Brass:Combo:Nickel");
	MATERIAL_MAP.put("1/16 Brushed Silver or Brushed Gold","Silver, Gold");
	MATERIAL_MAP.put("50 lb offset","Other");
	MATERIAL_MAP.put("80 lb matte paper stock","Paper");
	MATERIAL_MAP.put("Self cover","Other");
	MATERIAL_MAP.put("60 lb paper stock with gloss text and UV coated cover","Paper");
	MATERIAL_MAP.put("Printed weave cover","Other Fabric");
	MATERIAL_MAP.put("Morocco Leatherette","Other Leather/Suede");
	MATERIAL_MAP.put("Pacifica Vinyl Jacket","Vinyl");
	MATERIAL_MAP.put("Casemade Lexide Cover","Other");
	MATERIAL_MAP.put("70 Denier nylon with clear Vinyl front.","Nylon:Combo:Vinyl");
	MATERIAL_MAP.put("Drum Dyed Full Grain Cowhide","Leather");
	MATERIAL_MAP.put("100% Polyester, 4.57 oz per sq yard","Polyester");
	MATERIAL_MAP.put("Microfiber Terry Cloth","Other Fabric");
	
	BCNCOLOR_MAP.put("NAME","COLOR GROUP");
	BCNCOLOR_MAP.put("BURGUNDY","DARK RED");
	BCNCOLOR_MAP.put("BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("RED","MEDIUM RED");
	BCNCOLOR_MAP.put("YELLOW","MEDIUM YELLOW");
	BCNCOLOR_MAP.put("GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("NAVY BLUE","DARK BLUE");
	BCNCOLOR_MAP.put("NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("TAN","LIGHT BROWN");
	BCNCOLOR_MAP.put("GRAY","MEDIUM GRAY");
	BCNCOLOR_MAP.put("MULTI COLOR","MULTI COLOR");
	BCNCOLOR_MAP.put("WHITE GLOSS","MEDIUM WHITE");
	BCNCOLOR_MAP.put("BRUSHED BRASS","DARK YELLOW");
	BCNCOLOR_MAP.put("MEDIUM WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("SILVER","MEDIUM GRAY");
	BCNCOLOR_MAP.put("GOLD","DARK YELLOW");
	BCNCOLOR_MAP.put("ALMOND","MEDIUM WHITE");
	BCNCOLOR_MAP.put("BRUSHED SILVER","SILVER METAL");
	BCNCOLOR_MAP.put("BRUSHED GOLD","DARK YELLOW");
	BCNCOLOR_MAP.put("ENAMEL WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("ROYAL BLUE","BRIGHT BLUE");
	BCNCOLOR_MAP.put("CLEAR","CLEAR");
	BCNCOLOR_MAP.put("CUSTOM","OTHER");
	BCNCOLOR_MAP.put("MEDIUM GRAY","MEDIUM GRAY");
	BCNCOLOR_MAP.put("SILVER-BLACK","MEDIUM GRAY:COMBO:MEDIUM BLACK");
	BCNCOLOR_MAP.put("HUNTER GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("TRANSLUCENT BLUE","CLEAR BLUE");
	BCNCOLOR_MAP.put("WALNUT","MEDIUM BROWN");
	BCNCOLOR_MAP.put("OTHER","OTHER");
	BCNCOLOR_MAP.put("GOLD METAL","GOLD METAL");
	BCNCOLOR_MAP.put("SILVER METAL","SILVER METAL");
	BCNCOLOR_MAP.put("YELLOW GOLD","DARK YELLOW");
	BCNCOLOR_MAP.put("MEDIUM BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("BROWN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("ASSORTED","ASSORTED");
	BCNCOLOR_MAP.put("COPPER","COPPER METAL");
	BCNCOLOR_MAP.put("SILVER-GOLD","MEDIUM GRAY:COMBO:DARK YELLOW");
	BCNCOLOR_MAP.put("3054- BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("0924 CRIMSON","MEDIUM RED");
	BCNCOLOR_MAP.put("1041 BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("4515 TRUE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("CARMINE RED","MEDIUM RED");
	BCNCOLOR_MAP.put("BLACK - 1041","MEDIUM BLACK");
	BCNCOLOR_MAP.put("0783 AQUAMARINE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("4966 MIDNIGHT BLUE","DARK BLUE");
	BCNCOLOR_MAP.put("[1053 BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("CHARCOAL]","CHARCOAL]");
	BCNCOLOR_MAP.put("3404- TRUE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("0924- CRIMSON","MEDIUM RED");
	BCNCOLOR_MAP.put("4994- VIVID BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("CLEAR-BLUE","MULTI COLOR");
	BCNCOLOR_MAP.put("DISTRESSED BROWN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("DISTRESSED TAN","LIGHT BROWN");
	BCNCOLOR_MAP.put("ORANGE","MEDIUM ORANGE");
	BCNCOLOR_MAP.put("PURPLE","MEDIUM PURPLE");
	BCNCOLOR_MAP.put("AQUA BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("LIME","MEDIUM GREEN");
	BCNCOLOR_MAP.put("BLACK-GOLD","MEDIUM BLACK:COMBO:DARK YELLOW");
	BCNCOLOR_MAP.put("GOLD TONE","DARK YELLOW");
	BCNCOLOR_MAP.put("NATURAL OAK","MEDIUM BROWN");
	BCNCOLOR_MAP.put("1041- BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("MEDIUM BROWN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("VIOLET","MEDIUM PURPLE");
	BCNCOLOR_MAP.put("RED-BLACK","MEDIUM RED:COMBO:MEDIUM BLACK");
	BCNCOLOR_MAP.put("RED-CLEAR","MEDIUM RED:COMBO:MEDIUM CLEAR");
	BCNCOLOR_MAP.put("CHERRY WOOD","MEDIUM RED");
	BCNCOLOR_MAP.put("ANTIQUE WALNUT","MEDIUM BROWN");
	BCNCOLOR_MAP.put("BLACK-RED","MEDIUM BLACK:COMBO:MEDIUM RED");
	BCNCOLOR_MAP.put("LIME GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("PINK","MEDIUM PINK");
	BCNCOLOR_MAP.put("CHARCOAL","MEDIUM GRAY");
	BCNCOLOR_MAP.put("LIME CHEVRON","MEDIUM GREEN");
	BCNCOLOR_MAP.put("DARK RED","DARK RED");
	BCNCOLOR_MAP.put("DARK BROWN","DARK BROWN");
	BCNCOLOR_MAP.put("OLIVE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("CAMO","MULTI COLOR");
	BCNCOLOR_MAP.put("MAHOGANY","MEDIUM BROWN");
	BCNCOLOR_MAP.put("GUNMETAL","MEDIUM GRAY");
	BCNCOLOR_MAP.put("BLACK-SILVER","MEDIUM BLACK:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("ROSE GOLD","DARK YELLOW");
	BCNCOLOR_MAP.put("CREAM WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("FUCHSIA","MEDIUM PURPLE");
	BCNCOLOR_MAP.put("ESPRESSO","MEDIUM BROWN");
	BCNCOLOR_MAP.put("BRONZE","MEDIUM BROWN");
	BCNCOLOR_MAP.put("NATURAL PINE","MEDIUM BROWN");
	BCNCOLOR_MAP.put("FARMHOUSE WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("BLACK 03","MEDIUM BLACK");
	BCNCOLOR_MAP.put("BROWN 04","DARK BROWN");
	BCNCOLOR_MAP.put("CHESTNUT 06","MEDIUM BROWN");
	BCNCOLOR_MAP.put("BLACK AND SILVER STICK","MEDIUM BLACK:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("1710- BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("1310- SILVER","SILVER METAL");
	BCNCOLOR_MAP.put("0010- CHARCOAL","MEDIUM BLACK");
	BCNCOLOR_MAP.put("0070- CHARCOAL","MEDIUM BLACK");
	BCNCOLOR_MAP.put("MEDIUM RED","MEDIUM RED");
	BCNCOLOR_MAP.put("BRIGHT GREEN","BRIGHT GREEN");
	BCNCOLOR_MAP.put("BRASS","MEDIUM BROWN");
	BCNCOLOR_MAP.put("TEAL","MEDIUM GREEN");
	BCNCOLOR_MAP.put("ATHLETIC GOLD","DARK YELLOW");
	BCNCOLOR_MAP.put("IVORY","MEDIUM WHITE");
	BCNCOLOR_MAP.put("KELLY GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("FOREST GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("BROWN-SILVER","MEDIUM BROWN:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("BROWN-GOLD","MEDIUM BROWN:COMBO:DARK YELLOW");
	BCNCOLOR_MAP.put("DARK BROWN CHERRY","DARK BROWN");
	BCNCOLOR_MAP.put("OLD WORLD WALNUT","MEDIUM BROWN");
	BCNCOLOR_MAP.put("MARBLE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("WOOD","MEDIUM BROWN");
	BCNCOLOR_MAP.put("CLEAR-GOLD","MEDIUM CLEAR:COMBO:DARK YELLOW");
	BCNCOLOR_MAP.put("NAVY SPARKLE","DARK BLUE");
	BCNCOLOR_MAP.put("DISTRESSED MEDIUM BROWN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("BLACK 1041","MEDIUM BLACK");
	BCNCOLOR_MAP.put("HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("MEDIUM BROWN OAK","MEDIUM BROWN");
	BCNCOLOR_MAP.put("001 HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("006 HAMMERTONE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("016 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("043 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("ROYAL","MEDIUM BLUE");
	BCNCOLOR_MAP.put("NATURAL","LIGHT BROWN");
	BCNCOLOR_MAP.put("WHITE-BLACK","MEDIUM WHITE:COMBO:MEDIUM BLACK");
	BCNCOLOR_MAP.put("BLACK-CLEAR","MEDIUM BLACK:COMBO:MEDIUM CLEAR");
	BCNCOLOR_MAP.put("002 HAMMERTONE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("028 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("001 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("008 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("007 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("016 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("019 GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("020 NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("002 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("004 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("005 HAMMERTONE CONIFER","DARK GREEN");
	BCNCOLOR_MAP.put("006 HAMMERTONE COBALT","MEDIUM BLUE");
	BCNCOLOR_MAP.put("003 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("002 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("007 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("045 HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("047 HAMMERTONE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("087 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("088 HAMMERTONE ICE","LIGHT BLUE");
	BCNCOLOR_MAP.put("103 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("029 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("007 HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("008 HAMMERTONE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("059 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("008 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("001 GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("001 HAMMERTONE NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("025 HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("027 NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("014 GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("015 NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("023 GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("022 NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("035 HAMMERTONE GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("021 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("009 STAINLESS STEEL","SILVER METAL");
	BCNCOLOR_MAP.put("004 HAMMERTONE CONIFER","DARK GREEN");
	BCNCOLOR_MAP.put("005 HAMMERTONE COBALT","MEDIUM BLUE");
	BCNCOLOR_MAP.put("005 HAMMERTONE GREEN","DARK GREEN");
	BCNCOLOR_MAP.put("010 HAMMERTONE CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("011 HAMMERTONE ICE","LIGHT BLUE");
	BCNCOLOR_MAP.put("TRANSLUCENT PURPLE","CLEAR PURPLE");
	BCNCOLOR_MAP.put("TRANSLUCENT GREEN","CLEAR GREEN");
	BCNCOLOR_MAP.put("TRANSLUCENT RED","CLEAR RED");
	BCNCOLOR_MAP.put("FROSTED","DARK WHITE");
	BCNCOLOR_MAP.put("REFLEX BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("LIGHT BLUE","LIGHT BLUE");
	BCNCOLOR_MAP.put("OAK","LIGHT BROWN");
	BCNCOLOR_MAP.put("CHAMPAGNE","LIGHT GREEN");
	BCNCOLOR_MAP.put("GREEN-SILVER","MEDIUM GREEN:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("BROWN-BLACK","MEDIUM BROWN:COMBO:MEDIUM BLACK");
	BCNCOLOR_MAP.put("NAVY BLUE-SILVER","DARK BLUE:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("COPPER METAL","COPPER METAL");
	BCNCOLOR_MAP.put("CRIMSON","DARK RED");
	BCNCOLOR_MAP.put("DARK GREEN","DARK GREEN");
	BCNCOLOR_MAP.put("BORDEAUX PINK","MEDIUM PINK");
	BCNCOLOR_MAP.put("CINNEBAR RED","MEDIUM RED");
	BCNCOLOR_MAP.put("VIRIDIAN BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("CHARCOAL BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("LIME YELLOW","BRIGHT YELLOW");
	BCNCOLOR_MAP.put("GRAY-BLACK","MEDIUM GRAY:COMBO:MEDIUM BLACK");
	BCNCOLOR_MAP.put("FRAME- JET BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("FRAME- MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("FRAME- POLISHED BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("FRAME- ROSE GOLD","GOLD METAL");
	BCNCOLOR_MAP.put("FRAME- GUNMETAL","SILVER METAL");
	BCNCOLOR_MAP.put("FRAME- POLISHED WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("FRAME- WOODGRAIN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("FRAME- GHOST TEXT","OTHER");
	BCNCOLOR_MAP.put("FRAME- POLISHED CLEAR","CLEAR");
	BCNCOLOR_MAP.put("FRAME- MATTE BROWN GRAY","MEDIUM BROWN");
	BCNCOLOR_MAP.put("FRAME- MATTE BROWN TORTOISE","MEDIUM BROWN");
	BCNCOLOR_MAP.put("FRAME- MATTE BLUE","DARK BLUE");
	BCNCOLOR_MAP.put("FRAME- MATTE DARK BROWN","DARK BROWN");
	BCNCOLOR_MAP.put("MEDIUM GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("2065 CRIMSON","MEDIUM RED");
	BCNCOLOR_MAP.put("0784 AQUAMARINE-ASH-WHITE","LIGHT BLUE");
	BCNCOLOR_MAP.put("4952 FLAMINGO-CHARCOAL-WHITE","BRIGHT PINK");
	BCNCOLOR_MAP.put("0010 BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("0020 SILVER","MEDIUM GRAY");
	BCNCOLOR_MAP.put("0020 AQUA","LIGHT BLUE");
	BCNCOLOR_MAP.put("0030 CITRON","MULTI COLOR");
	BCNCOLOR_MAP.put("BK BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("BU BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("PM PLUM","MEDIUM PURPLE");
	BCNCOLOR_MAP.put("MEDUM BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("DARK PINK","DARK PINK");
	BCNCOLOR_MAP.put("003 MATTE BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("4512 BLACK-CRIMSON","MEDIUM BLACK");
	BCNCOLOR_MAP.put("BEIGE","LIGHT BROWN");
	BCNCOLOR_MAP.put("CAMOUFLAGE","CAMOUFLAGE BROWN");
	BCNCOLOR_MAP.put("CHROME METAL","CHROME METAL");
	BCNCOLOR_MAP.put("0100 SOFT BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("0200 POLAR WHITE","MEDIUM WHITE");
	BCNCOLOR_MAP.put("0400 CORAL RED","MEDIUM RED");
	BCNCOLOR_MAP.put("0500 AQUATIC BLUE","LIGHT BLUE");
	BCNCOLOR_MAP.put("LV LAVENDER","MEDIUM PURPLE");
	BCNCOLOR_MAP.put("MG MAGENTA","MEDIUM PINK");
	BCNCOLOR_MAP.put("NV NAVY BLUE","DARK BLUE");
	BCNCOLOR_MAP.put("PL PLUM","DARK PURPLE");
	BCNCOLOR_MAP.put("TE TEAL","BRIGHT GREEN");
	BCNCOLOR_MAP.put("H91 MODERN MEDLEY","MULTI COLOR");
	BCNCOLOR_MAP.put("H92 PAINTED MEDALLIONS","MULTI COLOR");
	BCNCOLOR_MAP.put("G24 RUMBA","MULTI COLOR");
	BCNCOLOR_MAP.put("G57 SANTIAGO","MULTI COLOR");
	BCNCOLOR_MAP.put("081 CLASSIC BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("I15 HAWTHORN ROSE","DARK RED");
	BCNCOLOR_MAP.put("H38 GEO MEDALLIONS","MULTI COLOR");
	BCNCOLOR_MAP.put("H34 GRANDE SANTIAGO","MULTI COLOR");
	BCNCOLOR_MAP.put("I21 DITZY DOTS","MULTI COLOR");
	BCNCOLOR_MAP.put("WASHED COWHIDE/WASHED BROWN CANVAS","MEDIUM BROWN");
	BCNCOLOR_MAP.put("VINTAGE BROWN","MEDIUM BROWN");
	BCNCOLOR_MAP.put("MEDIUM BLUE","MEDIUM BLUE");
	BCNCOLOR_MAP.put("DARK GRAY","DARK GRAY");
	BCNCOLOR_MAP.put("LAVENDER","LIGHT PURPLE");
	BCNCOLOR_MAP.put("NEON GREEN","MEDIUM GREEN");
	BCNCOLOR_MAP.put("LIGHT GRAY","LIGHT GRAY");
	BCNCOLOR_MAP.put("CRIMSON RED","MEDIUM RED");
	BCNCOLOR_MAP.put("GREY","MEDIUM GRAY");
	BCNCOLOR_MAP.put("SMOKE","MEDIUM GRAY");
	BCNCOLOR_MAP.put("CITRON GREEN","BRIGHT GREEN");
	BCNCOLOR_MAP.put("219 CLASSIC NAVY","DARK BLUE");
	BCNCOLOR_MAP.put("D52 CANYON SUNSET","DARK ORANGE");
	BCNCOLOR_MAP.put("1110 BLACK","MEDIUM BLACK");
	BCNCOLOR_MAP.put("1310 GRAY","LIGHT GRAY");
	BCNCOLOR_MAP.put("PM FUSCHIA","DARK PINK");
	BCNCOLOR_MAP.put("GY GRAY","MEDIUM GRAY");
	BCNCOLOR_MAP.put("CR CORAL","MEDIUM PINK");
	BCNCOLOR_MAP.put("GOLD/SILVER","DARK YELLOW:COMBO:MEDIUM GRAY");
	BCNCOLOR_MAP.put("001 FOUNDRY BLACK","MEDIUM BLACK");


	    }
	    public static String getColorGroup(String colorName){
			return BCNCOLOR_MAP.get(colorName.toUpperCase());
		}
}
